### ISSUE TITLE
Invalid PHP version

### ISSUE THREAD

**Issue by dreadnip** [szogyenyid/php-builder#4]
Your code contains `str_starts_with`, which was added in PHP8. Your composer.json claims compatibility with PHP 7.4.

Either bump the PHP version in composer.json or rework the code without PHP8 language features.

PS: This might interest you: https://www.php.net/manual/en/reflectionproperty.setaccessible.php

>  Note: As of PHP 8.1.0, calling this method has no effect; all properties are accessible by default. 

Might as well run PHP 8.1

**Comment by szogyenyid** [comment]
Thanks for the issue, replaced `str_starts_with`, it works on PHP7.4 now!
